packages:
  - libs/**/*
  - apps/*

# 依赖版本目录 - 统一管理所有包的依赖版本
# 策略：
# - 运行时依赖：统一版本管理
# - 框架特定开发依赖：统一版本管理
# - 全局开发工具（typescript, jest 等）：放根 package.json
catalog:
  # NestJS 核心
  '@nestjs/common': ^11.0.1
  '@nestjs/core': ^11.0.1
  '@nestjs/config': ^4.0.0
  '@nestjs/platform-fastify': ^11.0.1
  '@nestjs/testing': ^11.0.1
  '@nestjs/cli': ^11.0.0
  '@nestjs/schematics': ^11.0.0
  '@nestjs/terminus': ^11.0.0
  '@nestjs/swagger': 11.2.6
  '@nestjs/jwt': ^10.2.0
  '@nestjs/passport': ^10.0.3

  # Passport 认证
  passport: ^0.7.0
  passport-jwt: ^4.0.1

  # Fastify
  '@fastify/static': ^8.0.0
  '@fastify/cookie': ^11.0.0

  # 日志
  nestjs-pino: ^4.0.0
  pino: ^10.3.1
  pino-pretty: ^13.1.3

  # 上下文管理
  nestjs-cls: ^5.4.2

  # 核心
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.1

  # Redis
  ioredis: ^5.5.0
  redlock: ^4.2.0

  # 国际化
  nestjs-i18n: ^10.6.0
  class-validator: ^0.14.1
  class-transformer: ^0.5.1

  # MikroORM
  '@mikro-orm/core': 6.1.1
  '@mikro-orm/cli': 6.1.1
  '@mikro-orm/migrations': 6.1.1
  '@mikro-orm/nestjs': 6.1.1
  '@mikro-orm/postgresql': 6.1.1
  pg: ^8.13.3

  # 密码哈希
  argon2: ^0.40.3

  # 权限
  '@casl/ability': ^6.7.1

  # 认证
  better-auth: ^1.4.18

  # Zod
  zod: ^3.24.0

  # API 文档
  '@scalar/nestjs-api-reference': ^1.0.27

  # BDD 测试
  '@cucumber/cucumber': ^11.0.0
